import type {
  ClipParameterOverrides,
  ClipPrimaryView,
  DemoClipKill,
  DemoListEntry,
  DemoMaterialSelection,
} from "@/shared/types";
import {
  autoAddVictimView,
  addMaterialSelection,
  clearDemoSelectionState,
  clearMaterialSelections,
  fetchFullRoundPOVPlan,
  fullRoundPlanByDemo,
  fullRoundPlanErrorByDemo,
  getAllDemoKills,
  getClipPlayers,
  getClipRounds,
  getClipSelectMode,
  getDeathPlayers,
  getDeathRounds,
  getDemoMaterials,
  getFilteredKills,
  getFilteredRounds,
  getFullRoundPlayers,
  getFullRoundPOVSelection,
  getFullRoundPOVTrackingLabel,
  getFullRoundPlayerSteamID,
  getKillFilter,
  getMaterialSelectionCount,
  getMaterialSelections,
  getSelectedPlayerSteamID,
  isKillSelectedInDemo,
  patchKillFilter,
  resetKillFilterConditions,
  setAutoAddVictimView,
  setClipSelectMode,
  setDemoMaterials,
  setFullRoundPOVEnabled,
  setKillFilterRole,
  setSelectedPlayerSteamID,
  syncDefaultFullRoundPlayer,
  syncDefaultPlayerForRole,
  syncFullRoundPOVPlayer,
  removeMaterialSelection,
  updateMaterialClipOverrides,
  updateMaterialIncludeKiller,
  updateMaterialIncludeVictim,
  updateMaterialSpecModes,
  type ClipSelectMode,
  type DemoFullRoundPOVSelection,
  formatDuration,
} from "@/domains/clip-selection";
import {
  canSelectNext,
  canSelectPrev,
  clipReadyDemos,
  demoList,
  detailCollapsed,
  ensureClipDemoSelected as ensureClipDemoSelectedAction,
  onDemosSelected,
  removeDemoAt,
  selectDemoByKey,
  selectNextDemo,
  selectPrevDemo,
  selectedDemo,
  selectedEntry,
  selectedIndex,
  toggleDetailCollapsed,
  toggleSelected,
} from "@/domains/demo";

/**
 * Compatibility facade. The state and actions live in domain modules; this
 * module only keeps old feature imports working during page migration.
 */
export function useImportDemos() {
  return {
    demoList,
    selectedIndex,
    detailCollapsed,
    selectedEntry,
    selectedDemo,
    canSelectPrev,
    canSelectNext,
    clipReadyDemos,
    autoAddVictimView,
    setAutoAddVictimView,
    onDemosSelected,
    removeDemoAt,
    clearDemoSelectionState,
    toggleSelected,
    formatDuration,
    selectPrevDemo,
    selectNextDemo,
    toggleDetailCollapsed,
    selectDemoByKey,
    ensureClipDemoSelected,
    getClipPlayers,
    getDeathPlayers,
    getClipSelectMode,
    setClipSelectMode,
    getKillFilter,
    patchKillFilter,
    setKillFilterRole,
    resetKillFilterConditions,
    getAllDemoKills,
    getFilteredKills,
    getFilteredRounds,
    getFullRoundPlayers,
    getSelectedPlayerSteamID,
    setSelectedPlayerSteamID,
    getFullRoundPlayerSteamID,
    getClipRounds,
    getDeathRounds,
    getFullRoundPOVSelection,
    setFullRoundPOVEnabled,
    syncFullRoundPOVPlayer,
    fullRoundPlanByDemo,
    fullRoundPlanErrorByDemo,
    fetchFullRoundPOVPlan,
    getFullRoundPOVTrackingLabel,
    getMaterialSelections,
    getMaterialSelectionCount,
    addMaterialSelection,
    updateMaterialSpecModes,
    updateMaterialClipOverrides,
    updateMaterialIncludeVictim,
    updateMaterialIncludeKiller,
    removeMaterialSelection,
    isKillSelectedInDemo,
    clearMaterialSelections,
    syncDefaultFullRoundPlayer,
  };
}

function ensureClipDemoSelected(): DemoListEntry | null {
  const entry = ensureClipDemoSelectedAction();
  if (!entry) return null;
  // Selection defaults happen on parse and on this explicit navigation action.
  syncDefaultPlayerForRole(entry);
  syncDefaultFullRoundPlayer(entry);
  return entry;
}
